### PR TITLE
Add option for using a blank page or not when opening a new tab.

### PR DESCRIPTION
**Pull request by jesse-c**
I liked having the default tab page as opposed to the blank one so I added an option for the user to choose. It defaults to the blank page.

### CODE REVIEW

**Comment by TylerCharlesworth** [comment]
@jesse-c Thanks for the contribution! Curious why somebody would want the extension installed but would not want to show the blank page?

**Comment by jesse-c** [comment]
I suppose it does seem a bit odd! For me it was because sometimes I wanted to start using that tab (after no longer using it as a separator) and liked having the shortcuts, etc. on the default tab page.

**Comment by TylerCharlesworth** [comment]
@jesse-c: That makes sense, I suppose :-) I've merged your commit -- will make a couple of changes/additions and publish soon.

**Review by TylerCharlesworth — COMMENTED** [review]
👍

**Comment by TylerCharlesworth** [comment]
@jesse-c: Heads up that this was changed a bit for the 1.3 release! Live now 👍 

Not using the `chrome_url_overrides` made the standard behavior a bit worse -- location bar had ugly extension ID text in it instead of blank, favicon was present instead of blank, flicker of normal new tab page before blank page appearing, and requiring the "tabs" permission is a bit invasive for users just looking for a clean tab page. 

The compromise here is that there's now a link in the popup menu that will take you directly to the extension in Manage Extensions. Hopefully that helps cover your use-case somewhat!

**Comment by jesse-c** [comment]
@TylerCharlesworth Thanks for giving me an update! Yup, as it is now works well for me. 😄

**Pull request merged**
